baseurl = "http://veronicaray.com/"
languageCode = "en-us"
title = "Nerdonica"
theme = "ananke"
publishDir = "docs"

SectionPagesMenu = "main"

[params]
  description = "Veronica Ray's blog"
  linkedin = "https://www.linkedin.com/in/veronicalray/"
  featured_image = ""
